# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burrow < Formula
  desc "Dev tunnel CLI wrapping Cloudflare Tunnel with team-friendly persistent URLs"
  homepage "https://github.com/frank-chris/burrow"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frank-chris/burrow/releases/download/v0.2.0/burrow_darwin_amd64.tar.gz"
      sha256 "0e167d42f04d08355d1bf8c9876a7b623f45c1e55eecf85e764394efe997a1c2"

      define_method(:install) do
        bin.install "burrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frank-chris/burrow/releases/download/v0.2.0/burrow_darwin_arm64.tar.gz"
      sha256 "1770a2a65c85c24cde70789fa3fc20148de44d6994cecadeb6fa2af51c60a381"

      define_method(:install) do
        bin.install "burrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-chris/burrow/releases/download/v0.2.0/burrow_linux_amd64.tar.gz"
      sha256 "58f2ba7d5b71d0a49eb32253efd3b3aa7095d07633bec1d81880050f24a1fb3c"
      define_method(:install) do
        bin.install "burrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-chris/burrow/releases/download/v0.2.0/burrow_linux_arm64.tar.gz"
      sha256 "cada2e496db5b1540eecb9e8c92a3180843995af50835f0349271b3c142b9923"
      define_method(:install) do
        bin.install "burrow"
      end
    end
  end

  test do
    system "#{bin}/burrow", "--version"
  end
end
