# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burrow < Formula
  desc "Dev tunnel CLI wrapping Cloudflare Tunnel with team-friendly persistent URLs"
  homepage "https://github.com/frank-chris/burrow"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/frank-chris/burrow/releases/download/v0.2.1/burrow_darwin_amd64.tar.gz"
      sha256 "2e188665a9847d35346a2a95e89479298a28358c6de49acb2912d0b0c6e2f684"

      define_method(:install) do
        bin.install "burrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/frank-chris/burrow/releases/download/v0.2.1/burrow_darwin_arm64.tar.gz"
      sha256 "ee7d5f5bfa8871901060631714a115dcc5f23ce93127ad168739891a9470ddcd"

      define_method(:install) do
        bin.install "burrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-chris/burrow/releases/download/v0.2.1/burrow_linux_amd64.tar.gz"
      sha256 "e8b1ee1e019aa1235c1036891233c0b1f77c0995be69afca18b6f79a9097035e"
      define_method(:install) do
        bin.install "burrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/frank-chris/burrow/releases/download/v0.2.1/burrow_linux_arm64.tar.gz"
      sha256 "f14ab242869084dcf75c2368d700f62b661b9d51f1710328e8600439d2472d49"
      define_method(:install) do
        bin.install "burrow"
      end
    end
  end

  test do
    system "#{bin}/burrow", "--version"
  end
end
